#!/usr/bin/env python

from facepy import GraphAPI

def graph_client(token="CAACEdEose0cBADVdTLThVgsoMhYbkYpHcn4ZCu8XAdZBNxa2C9QAss8Qpv35ANSmLVn2MeAFLjCucASjCBbhoNaHde7EEsEp4O8OZBWXTU8ayzUuuserhzz8n9qUtVKZAj5GbKgTioiZCfk6kZC1Ae5KJ9kDVhcva9d4h5U2fHZCJZB08vsMWgPufMUoffHDdc6ZCow89yOUZCFWgXHpfqcOLz"):
  return GraphAPI(token)